version: '2.1'

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: mg_telegram
            POSTGRES_PASSWORD: mg_telegram
            POSTGRES_DATABASE: mg_telegram
        ports:
            - ${POSTGRES_ADDRESS:-127.0.0.1:5434}:5432

    mg_migrate:
        image: golang:1.9.3-stretch
        working_dir: /mg_telegram_migrate
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./:/mg_telegram_migrate/
        links:
            - postgres
        depends_on:
            - postgres
        command: make migrate

    mg_telegram:
        image: hub.retailcrm.pro/message-gateway/transport-telegram:latest
        restart: always
        volumes:
            - ./config.yml:/config.yml
        ports:
            - ${MG_TELEGRAM_ADDRESS:-3001}:3001
        links:
            - postgres
        depends_on:
            - mg_migrate
